# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 18:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Code')),
                ('stops', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=2), default=[], size=None, verbose_name='Stops (Ordered)')),
                ('terminals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=[], size=2, verbose_name='Terminals')),
                ('departure_times', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), default=[], null=True, size=None), default=[], size=6, verbose_name='Departure Times')),
            ],
            options={
                'verbose_name': 'Route',
                'ordering': ['code'],
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=64, verbose_name='Label')),
                ('coor', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2, verbose_name='Coordination')),
            ],
            options={
                'verbose_name': 'Stop',
                'ordering': ['label'],
                'verbose_name_plural': 'Stops',
            },
        ),
    ]
