# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 16:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Route',
                'ordering': ['code'],
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=32, verbose_name='Label')),
                ('coor', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2, verbose_name='Coordination')),
            ],
            options={
                'verbose_name': 'Stop',
                'ordering': ['label'],
                'verbose_name_plural': 'Stops',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(related_name='routes', to='izmir.Stop', verbose_name='Stops'),
        ),
    ]
