# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 19:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izmir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='terminals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=[], size=2, verbose_name='Terminals'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(blank=True, null=True, related_name='routes', to='izmir.Stop', verbose_name='Stops'),
        ),
    ]
