# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 09:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izmir', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='departure_times',
        ),
        migrations.RemoveField(
            model_name='route',
            name='stops',
        ),
        migrations.AddField(
            model_name='route',
            name='departure_times_backwards',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), default=[], null=True, size=None), default=[], size=6, verbose_name='Departure Times (Backwards)'),
        ),
        migrations.AddField(
            model_name='route',
            name='departure_times_forwards',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), default=[], null=True, size=None), default=[], size=6, verbose_name='Departure Times (Forwards)'),
        ),
        migrations.AddField(
            model_name='route',
            name='stops_backwards',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=2), default=[], size=None, verbose_name='Stops Backwards (Ordered)'),
        ),
        migrations.AddField(
            model_name='route',
            name='stops_forwards',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=2), default=[], size=None, verbose_name='Stops Forwards (Ordered)'),
        ),
    ]
