# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 13:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izmir', '0003_auto_20160909_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='stops_backwards',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=2), default=[], size=None, verbose_name='Stops Backwards (Ordered)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stops_forwards',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=2), default=[], size=None, verbose_name='Stops Forwards (Ordered)'),
        ),
    ]
