# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 07:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izmir', '0004_auto_20160712_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='departure_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), default=[], size=6, verbose_name='Departure Times'),
        ),
    ]
